### ISSUE TITLE
No longer seems to work with volume mapping

### ISSUE THREAD

**Issue by btrscott** [dgraziotin/osx-docker-mysql#3] opened 2016-04-19 13:21 UTC
OSX 10.11.4
Docker Toolbox 1.11.0

Seems like more docker machine to mac permission errors.

docker run -d -p 3306:3306 -v ${PWD}/databases/mysql:/var/lib/mysql --name mysql2 -e CREATE_MYSQL_BASIC_USER_AND_DB="true",MYSQL_USER_NAME="scott",MYSQL_USER_PASS="test" dgraziotin/mysql

Scotts-iMac:~ scott$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
fcfe927e8510        dgraziotin/mysql    "/run.sh"           7 seconds ago       Up 6 seconds        0.0.0.0:3306->3306/tcp   mysql2
Scotts-iMac:~ scott$ docker logs mysql2
chown: changing ownership of '/var/lib/mysql': Operation not permitted
chown: changing ownership of '/var/lib/mysql': Operation not permitted
=> An empty or uninitialized MySQL volume is detected in /var/lib/mysql
=> Installing MySQL ...
=> Done!
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
Scotts-iMac:~ scott$ docker exec -it mysql2 bash
root@fcfe927e8510:/# cd /var/log/mysql
root@fcfe927e8510:/var/log/mysql# ls
error.log
root@fcfe927e8510:/var/log/mysql# cat error.log
160317 10:52:27 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160317 10:52:27 [Note] Plugin 'FEDERATED' is disabled.
160317 10:52:27 InnoDB: The InnoDB memory heap is disabled
160317 10:52:27 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160317 10:52:27 InnoDB: Compressed tables use zlib 1.2.8
160317 10:52:27 InnoDB: Using Linux native AIO
160317 10:52:27 InnoDB: Initializing buffer pool, size = 128.0M
160317 10:52:27 InnoDB: Completed initialization of buffer pool
InnoDB: The first specified data file ./ibdata1 did not exist:
InnoDB: a new database to be created!
160317 10:52:27  InnoDB: Setting file ./ibdata1 size to 10 MB
InnoDB: Database physically writes the file full: wait...
160317 10:52:28  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile0 size to 5 MB
InnoDB: Database physically writes the file full: wait...
160317 10:52:28  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile1 size to 5 MB
InnoDB: Database physically writes the file full: wait...
InnoDB: Doublewrite buffer not found: creating new
InnoDB: Doublewrite buffer created
InnoDB: 127 rollback segment(s) active.
InnoDB: Creating foreign key constraint system tables
InnoDB: Foreign key constraint system tables created
160317 10:52:28  InnoDB: Waiting for the background threads to start
160317 10:52:29 InnoDB: 5.5.47 started; log sequence number 0
160317 10:52:29  InnoDB: Starting shutdown...
160317 10:52:29  InnoDB: Shutdown completed; log sequence number 1595675
160317 10:52:29 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160317 10:52:29 [Note] Plugin 'FEDERATED' is disabled.
160317 10:52:29 InnoDB: The InnoDB memory heap is disabled
160317 10:52:29 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160317 10:52:29 InnoDB: Compressed tables use zlib 1.2.8
160317 10:52:29 InnoDB: Using Linux native AIO
160317 10:52:29 InnoDB: Initializing buffer pool, size = 128.0M
160317 10:52:29 InnoDB: Completed initialization of buffer pool
160317 10:52:29 InnoDB: highest supported file format is Barracuda.
160317 10:52:29  InnoDB: Waiting for the background threads to start
160317 10:52:30 InnoDB: 5.5.47 started; log sequence number 1595675
ERROR: 1064  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE user ADD column Show_view_priv enum('N','Y') CHARACTER SET utf8 NOT ' at line 1
160317 10:52:30 [ERROR] Aborting

160317 10:52:30  InnoDB: Starting shutdown...
160317 10:52:31  InnoDB: Shutdown completed; log sequence number 1595675
160317 10:52:31 [Note] /usr/sbin/mysqld: Shutdown complete

160317 10:52:31 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160317 10:52:31 [Note] Plugin 'FEDERATED' is disabled.
160317 10:52:31 InnoDB: The InnoDB memory heap is disabled
160317 10:52:31 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160317 10:52:31 InnoDB: Compressed tables use zlib 1.2.8
160317 10:52:31 InnoDB: Using Linux native AIO
160317 10:52:31 InnoDB: Initializing buffer pool, size = 128.0M
160317 10:52:31 InnoDB: Completed initialization of buffer pool
160317 10:52:31 InnoDB: highest supported file format is Barracuda.
160317 10:52:31  InnoDB: Waiting for the background threads to start
160317 10:52:32 InnoDB: 5.5.47 started; log sequence number 1595675
160317 10:52:32  InnoDB: Starting shutdown...
160317 10:52:33  InnoDB: Shutdown completed; log sequence number 1595675
160317 10:52:33 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160317 10:52:33 [Note] Plugin 'FEDERATED' is disabled.
160317 10:52:33 InnoDB: The InnoDB memory heap is disabled
160317 10:52:33 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160317 10:52:33 InnoDB: Compressed tables use zlib 1.2.8
160317 10:52:33 InnoDB: Using Linux native AIO
160317 10:52:33 InnoDB: Initializing buffer pool, size = 128.0M
160317 10:52:33 InnoDB: Completed initialization of buffer pool
160317 10:52:33 InnoDB: highest supported file format is Barracuda.
160317 10:52:33  InnoDB: Waiting for the background threads to start
160317 10:52:34 InnoDB: 5.5.47 started; log sequence number 1595675
ERROR: 1050  Table 'plugin' already exists
160317 10:52:34 [ERROR] Aborting

160317 10:52:34  InnoDB: Starting shutdown...
160317 10:52:35  InnoDB: Shutdown completed; log sequence number 1595675
160317 10:52:35 [Note] /usr/sbin/mysqld: Shutdown complete

160419 13:14:15 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
160419 13:14:15 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
160419 13:14:15 [Note] /usr/sbin/mysqld (mysqld 5.5.47-0ubuntu0.14.04.1) starting as process 381 ...
160419 13:14:15 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160419 13:14:15 [Note] Plugin 'FEDERATED' is disabled.
/usr/sbin/mysqld: Table 'mysql.plugin' doesn't exist
160419 13:14:15 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
160419 13:14:15 InnoDB: The InnoDB memory heap is disabled
160419 13:14:15 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160419 13:14:15 InnoDB: Compressed tables use zlib 1.2.8
160419 13:14:15 InnoDB: Using Linux native AIO
160419 13:14:15 InnoDB: Initializing buffer pool, size = 128.0M
160419 13:14:15 InnoDB: Completed initialization of buffer pool
InnoDB: The first specified data file ./ibdata1 did not exist:
InnoDB: a new database to be created!
160419 13:14:15  InnoDB: Setting file ./ibdata1 size to 10 MB
InnoDB: Database physically writes the file full: wait...
160419 13:14:18  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile0 size to 5 MB
InnoDB: Database physically writes the file full: wait...
160419 13:14:18  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
InnoDB: Setting log file ./ib_logfile1 size to 5 MB
InnoDB: Database physically writes the file full: wait...
InnoDB: Doublewrite buffer not found: creating new
InnoDB: Doublewrite buffer created
InnoDB: 127 rollback segment(s) active.
InnoDB: Creating foreign key constraint system tables
InnoDB: Foreign key constraint system tables created
160419 13:14:19  InnoDB: Waiting for the background threads to start
160419 13:14:20 InnoDB: 5.5.47 started; log sequence number 0
160419 13:14:20 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
160419 13:14:20 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
160419 13:14:20 [Note] Server socket created on IP: '0.0.0.0'.
160419 13:14:20 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.host' doesn't exist
160419 13:14:20 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
root@fcfe927e8510:/var/log/mysql#

chown: changing ownership of '/var/lib/mysql': Operation not permitted
chown: changing ownership of '/var/lib/mysql': Operation not permitted
=> An empty or uninitialized MySQL volume is detected in /var/lib/mysql
=> Installing MySQL ...
=> Done!
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup
=> Waiting for confirmation of MySQL service startup

**Comment by dgraziotin** [comment] 2016-04-21 12:14
I'll investigate as soon as I've got an Internet connection at my new home.
Thanks!

**Comment by dgraziotin** [comment] 2016-05-14 15:29
Hi. Finally got the time to look at this. I cannot reproduce this issue. Are you using the latest version of the image?

Please reopen in case.

```
daniel@Abadah ~ $ cd /tmp/
daniel@Abadah /tmp $ mkdir docker
daniel@Abadah /tmp $ cd docker
daniel@Abadah /tmp/docker $ mkdir databases
daniel@Abadah /tmp/docker $ mkdir databases/mysql
daniel@Abadah /tmp/docker $ docker run -d -p 3306:3306 -v ${PWD}/databases/mysql:/var/lib/mysql --name test -e CREATE_MYSQL_BASIC_USER_AND_DB="true" -e MYSQL_USER_NAME="scott" -e MYSQL_USER_PASS="test" dgraziotin/mysql
1be807f8a4eead7840122156c89ac47f7d1baf2243ad69769beb3bd9d8d2e636
daniel@Abadah /tmp/docker $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
1be807f8a4ee        dgraziotin/mysql    "/run.sh"           23 seconds ago      Up 23 seconds       0.0.0.0:3306->3306/tcp   test
daniel@Abadah /tmp/docker $ docker logs test
=> An empty or uninitialized MySQL volume is detected in /var/lib/mysql
=> Installing MySQL ...
=> Done!
=> Waiting for confirmation of MySQL service startup
=> Creating MySQL admin user with random password
=> Done!
========================================================================
You can now connect to this MySQL Server with O8zVluoq8Zru

    mysql -uadmin -pO8zVluoq8Zru -h<host> -P<port>

Please remember to change the above password as soon as possible!
MySQL user 'root' has no password but only allows local connections

We also created
A database called 'db' and
a user called 'scott' with password 'test'
'scott' has full access on 'db'
enjoy!
========================================================================
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2016-05-14 15:27:54,456 CRIT Supervisor running as root (no user in config file)
2016-05-14 15:27:54,456 WARN Included extra file "/etc/supervisor/conf.d/supervisord-mysqld.conf" during parsing
2016-05-14 15:27:54,481 INFO RPC interface 'supervisor' initialized
2016-05-14 15:27:54,482 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-05-14 15:27:54,482 INFO supervisord started with pid 1
2016-05-14 15:27:55,483 INFO spawned: 'mysqld' with pid 440
2016-05-14 15:27:56,640 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
daniel@Abadah /tmp/docker $
```

**Comment by tanis2000** [comment] 2016-09-07 08:06
I've just found a solution to this. You should run `mysqld --initialize` before starting mysqld_safe.
It solved the problem for me. @dgraziotin could you please add it to the setup script in this docker image? Thanks!

**Comment by dgraziotin** [comment] 2016-09-07 08:08
@tanis2000 thanks for this. As of Docker for Mac 1.12, [this project is no longer necessary](https://ineed.coffee/4064/my-os-x-docker-images-for-lamp-are-no-longer-necessary/). Better to switch to the official packages!

**Comment by tanis2000** [comment] 2016-09-07 08:18
`docker --version`
    Docker version 1.12.1, build 23cf638

All of the other mysql docker images aren't working for me. They all can't write to the shared volume. Yours is still the only one working. Is there anything that I should add to the docker-compose definition file to enable write support?

**Comment by dgraziotin** [comment] 2016-09-07 08:22
@tanis2000 well, in that case..feel free to PR here!

**Comment by dgraziotin** [comment] 2016-09-09 16:41
@btrscott this seems to be fixed now. Can you confirm?

**Closed as completed by dgraziotin** 2016-09-09 16:41 UTC
